version: "3.9"
services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile-debian
    links:
      - redis:redis.docker
    volumes:
      - ./api-gateway-config:/etc/api-gateway
    ports:
      - "80:80"
      - "9113:9113"
    environment:
      - LOG_LEVEL=info
      - DEBUG=true
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
